MyWidgets:

<MyWidgets>

    Label:
        id: label1
        text:'firstName:'
        pos:(50,570)
        font_size:30
        color:(60/255,90/255,160/255,1)
    Button:
        text:'click me!'
        pos:(20,450)
        size:(480,58)
        font_size:30
        on_press:root.btn_press()
    TextInput:
        id: textfieald
        multiline:False
        pos:(200,600)
        size:(300,38)
        font_size:20


</MyWidgets>